mysql:
  username: root
  password: "root"
  database: undefined
  url: "127.0.0.1:3306"

help:
  create: "/<cmd> create [account-alias]\nCreates a new account"
  info: "/<cmd> info\nOpens the Bank GUI with Information and options"
  pay: "/<cmd> pay <username> <account-id> <amount> <reason>\nShows you a pay menu"